version: '3.8'

services:
  awsblogs-mcp-sse:
    build:
      context: .
      dockerfile: Dockerfile.sse
    container_name: awsblogs-mcp-server-sse
    ports:
      - "8807:8807"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
